light = {
'surface-container': '#f1f5f9',
'on-surface-variant': '#475569',
'on-primary-container': '#7f1d1d',
'surface': '#ffffff',
'on-secondary': '#ffffff',
'on-secondary-fixed-variant': '#7f1d1d',
'surface-container-high': '#e2e8f0',
'secondary-fixed-dim': '#fca5a5',
'on-error': '#ffffff',
'outline-variant': '#cbd5e1',
'on-tertiary-fixed-variant': '#334155',
'secondary-fixed': '#fecaca',
'on-surface': '#0f172a',
'on-primary': '#ffffff',
'surface-container-lowest': '#ffffff',
'primary-container': '#fee2e2',
'primary-fixed': '#fecaca',
'on-secondary-container': '#7f1d1d',
'secondary-container': '#fee2e2',
'surface-dim': '#f8fafc',
'surface-container-low': '#f8fafc',
'background': '#ffffff',
'secondary': '#ef4444',
'tertiary-container': '#f1f5f9',
'error-container': '#fee2e2',
'outline': '#94a3b8',
'surface-bright': '#ffffff',
'primary-fixed-dim': '#fca5a5',
'on-primary-fixed': '#7f1d1d',
'tertiary-fixed-dim': '#cbd5e1',
'error': '#dc2626',
'tertiary': '#64748b',
'primary': '#dc2626',
'tertiary-fixed': '#e2e8f0',
'on-tertiary-fixed': '#0f172a',
'on-tertiary': '#ffffff',
'surface-tint': '#dc2626',
'surface-container-highest': '#cbd5e1',
'inverse-on-surface': '#f1f5f9',
'on-error-container': '#7f1d1d',
'on-background': '#0f172a',
'surface-variant': '#f1f5f9',
'on-secondary-fixed': '#450a0a',
'on-tertiary-container': '#0f172a',
'on-primary-fixed-variant': '#7f1d1d',
'inverse-primary': '#fca5a5',
'inverse-surface': '#1e293b'
}

dark = {
'surface-container': '#2c1b1b',
'on-surface-variant': '#d2c3c2',
'on-primary-container': '#8f7675',
'surface': '#1e0f0f',
'on-secondary': '#3c2f00',
'on-secondary-fixed-variant': '#574500',
'surface-container-high': '#372625',
'secondary-fixed-dim': '#e9c349',
'on-error': '#690005',
'outline-variant': '#4f4444',
'on-tertiary-fixed-variant': '#454745',
'secondary-fixed': '#ffe088',
'on-surface': '#f9dcdb',
'on-primary': '#3f2c2b',
'surface-container-lowest': '#180a0a',
'primary-container': '#1a0b0b',
'primary-fixed': '#fbdbda',
'on-secondary-container': '#342800',
'secondary-container': '#af8d11',
'surface-dim': '#1e0f0f',
'surface-container-low': '#271717',
'background': '#1e0f0f',
'secondary': '#e9c349',
'tertiary-container': '#0e100e',
'error-container': '#93000a',
'outline': '#9b8e8d',
'surface-bright': '#473434',
'primary-fixed-dim': '#ddc0bf',
'on-primary-fixed': '#281717',
'tertiary-fixed-dim': '#c6c7c3',
'error': '#ffb4ab',
'tertiary': '#c6c7c3',
'primary': '#ddc0bf',
'tertiary-fixed': '#e2e3df',
'on-tertiary-fixed': '#1a1c1a',
'on-tertiary': '#2f312e',
'surface-tint': '#ddc0bf',
'surface-container-highest': '#423030',
'inverse-on-surface': '#3e2c2c',
'on-error-container': '#ffdad6',
'on-background': '#f9dcdb',
'surface-variant': '#423030',
'on-secondary-fixed': '#241a00',
'on-tertiary-container': '#7b7c79',
'on-primary-fixed-variant': '#574141',
'inverse-primary': '#705958',
'inverse-surface': '#f9dcdb'
}

with open("e:\\ATS_UserUI\\scripts\\output.txt", "w") as f:
    f.write(':root {\n')
    for k, v in light.items():
        f.write(f'  --color-{k}: {v};\n')
    f.write('}\n\n.dark {\n')
    for k, v in dark.items():
        f.write(f'  --color-{k}: {v};\n')
    f.write('}\n\ncolors: {\n')
    for k in light.keys():
        f.write(f'  "{k}": "var(--color-{k})",\n')
    f.write('}\n')
